## STATUS (LOV)
CREATE TABLE STATUS_LOV (
    STATUS_ID     NUMBER PRIMARY KEY,
    STATUS_NAME   VARCHAR2(100) NOT NULL,
    STATUS_ICON   VARCHAR2(50),
    DELETED_YN    CHAR(2) DEFAULT 'NO'
);

## LEAD
CREATE TABLE LEAD (
    LEAD_ID                     NUMBER PRIMARY KEY,
    APPOINTMENT_STATUS_ID       NUMBER,
    SALES_STATUS_ID             NUMBER,
    CONSTRAINT FK_LEAD_APPT
        FOREIGN KEY (APPOINTMENT_STATUS_ID)
        REFERENCES STATUS_LOV (STATUS_ID),
    CONSTRAINT FK_LEAD_SALES
        FOREIGN KEY (SALES_STATUS_ID)
        REFERENCES STATUS_LOV (STATUS_ID)
);

## CUSTOMER
CREATE TABLE CUSTOMER (
    CUST_ID                     NUMBER PRIMARY KEY,
    CUST_NAME                   VARCHAR2(100),
    CUST_SURNAME                VARCHAR2(100),
    CUST_LEAD_FK                NUMBER NOT NULL,
    ORDER_DATE                  DATE NOT NULL,
    INTERNAL_STATUS_ID          NUMBER,
    TECH_STATUS_ID              NUMBER,
    DELETED_YN                  CHAR(2) DEFAULT 'NO',

    CONSTRAINT FK_CUST_LEAD
        FOREIGN KEY (CUST_LEAD_FK)
        REFERENCES LEAD (LEAD_ID),

    CONSTRAINT FK_CUST_INTERNAL
        FOREIGN KEY (INTERNAL_STATUS_ID)
        REFERENCES STATUS_LOV (STATUS_ID),

    CONSTRAINT FK_CUST_TECH
        FOREIGN KEY (TECH_STATUS_ID)
        REFERENCES STATUS_LOV (STATUS_ID)
);

## Sample data (minimal, readable)
INSERT INTO STATUS_LOV VALUES (1, 'New',        '🟢', 'NO');
INSERT INTO STATUS_LOV VALUES (2, 'In Progress','🟡', 'NO');
INSERT INTO STATUS_LOV VALUES (3, 'Completed',  '✅', 'NO');
INSERT INTO STATUS_LOV VALUES (4, 'Canceled',   '❌', 'NO');

INSERT INTO LEAD VALUES (1001, 1, 2);
INSERT INTO LEAD VALUES (1002, 2, 3);

INSERT INTO CUSTOMER VALUES
(2001, 'John', 'Doe', 1001, SYSDATE-3, 2, 3, 'NO');

INSERT INTO CUSTOMER VALUES
(2002, 'Jane', 'Smith', 1002, SYSDATE-10, 3, 3, 'NO');

COMMIT;
