## STATUS (LOV)
CREATE TABLE STATUS_LOV (
    STATUS_ID     NUMBER PRIMARY KEY,
    STATUS_NAME   VARCHAR2(100) NOT NULL,
    STATUS_ICON   VARCHAR2(50),
    DELETED_YN    CHAR(2) DEFAULT 'NO'
);

## LEAD
CREATE TABLE LEAD (
    LEAD_ID                     NUMBER PRIMARY KEY,
    APPOINTMENT_STATUS_ID       NUMBER,
    SALES_STATUS_ID             NUMBER,
    CONSTRAINT FK_LEAD_APPT
        FOREIGN KEY (APPOINTMENT_STATUS_ID)
        REFERENCES STATUS_LOV (STATUS_ID),
    CONSTRAINT FK_LEAD_SALES
        FOREIGN KEY (SALES_STATUS_ID)
        REFERENCES STATUS_LOV (STATUS_ID)
);

## CUSTOMER
CREATE TABLE CUSTOMER (
    CUST_ID                     NUMBER PRIMARY KEY,
    CUST_NAME                   VARCHAR2(100),
    CUST_SURNAME                VARCHAR2(100),
    CUST_LEAD_FK                NUMBER NOT NULL,
    ORDER_DATE                  DATE NOT NULL,
    INTERNAL_STATUS_ID          NUMBER,
    TECH_STATUS_ID              NUMBER,
    DELETED_YN                  CHAR(2) DEFAULT 'NO',

    CONSTRAINT FK_CUST_LEAD
        FOREIGN KEY (CUST_LEAD_FK)
        REFERENCES LEAD (LEAD_ID),

    CONSTRAINT FK_CUST_INTERNAL
        FOREIGN KEY (INTERNAL_STATUS_ID)
        REFERENCES STATUS_LOV (STATUS_ID),

    CONSTRAINT FK_CUST_TECH
        FOREIGN KEY (TECH_STATUS_ID)
        REFERENCES STATUS_LOV (STATUS_ID)
);


